# Base image for your application
FROM python:3.13-slim

# Environment variables for Python performance and logging
ENV PYTHONUNBUFFERED=1

# Set the working directory inside the container
WORKDIR /app

# Install necessary system dependencies (e.g., for psycopg2 if you use a real DB)
RUN apt-get update && apt-get install -y --no-install-recommends libpq5 \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src/common /app/common
COPY src/game_engine /app/game_engine
COPY assets/cards /app/cards

# Expose the application port
EXPOSE 5000
CMD ["flask", "--app=game_engine.app:create_test_app", "run", "--cert=/run/secrets/game-engine.crt", "--key=/run/secrets/game-engine.key", "--host=0.0.0.0", "--port=5000"]
