FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src/matchmaking /app/matchmaking
COPY src/common /app/common

EXPOSE 5000

CMD ["flask", "--app=matchmaking.app:create_test_app", "run", "--cert=/run/secrets/matchmaking.crt", "--key=/run/secrets/matchmaking.key", "--host=0.0.0.0", "--port=5000"]
